[package]
name="rf-engine"
version.workspace=true
edition.workspace=true
license.workspace=true
[dependencies]
bytes.workspace=true
rf-device={path="../rf-device"}
rf-dsp={path="../rf-dsp"}
rf-types={path="../rf-types"}
tokio.workspace=true

tracing.workspace=true
num-complex.workspace=true
serde.workspace=true
serde_json.workspace=true
